// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class PavanputraHanuman
{
        public const string achievement_veer_gada = "CgkI74_B_vEQEAIQAg"; // <GPGSID>
        public const string leaderboard_top_pavan_putra_score = "CgkI74_B_vEQEAIQBg"; // <GPGSID>
        public const string achievement_param_veer_gada = "CgkI74_B_vEQEAIQAw"; // <GPGSID>
        public const string achievement_shaurya_gada = "CgkI74_B_vEQEAIQAQ"; // <GPGSID>
        public const string achievement_atoot_ratn_gada = "CgkI74_B_vEQEAIQBQ"; // <GPGSID>
        public const string achievement_yudh_kirti_gada = "CgkI74_B_vEQEAIQBA"; // <GPGSID>

}

